"""initial schema

Revision ID: 26694fd0d572
Revises: 
Create Date: 2026-07-12 23:24:32.150835

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26694fd0d572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_triggers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('task_template_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_triggers_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_triggers_project_id'), ['project_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_project_id'), ['project_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('auto_aggregate', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_project_id'), ['project_id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('goal_id', sa.String(length=26), nullable=True),
    sa.Column('milestone_id', sa.String(length=26), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('cron_template_id', sa.String(length=26), nullable=True),
    sa.Column('emit_event_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cron_template_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['emit_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_dequeue', ['project_id', 'assignee', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_task_id'), ['task_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('depends_on_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=True),
    sa.Column('task_id', sa.String(length=26), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_task_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_project_id'))

    op.drop_table('telemetry')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_task_id'))

    op.drop_table('messages')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_goal_id'))
        batch_op.drop_index('idx_tasks_dequeue')

    op.drop_table('tasks')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_project_id'))

    op.drop_table('goals')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_events_name'))

    op.drop_table('events')
    with op.batch_alter_table('event_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_triggers_project_id'))
        batch_op.drop_index(batch_op.f('ix_event_triggers_event_name'))

    op.drop_table('event_triggers')
    op.drop_table('projects')
    # ### end Alembic commands ###
